# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: microservice-a
spec:
  type: ClusterIP # Change to LoadBalancer if external access is needed
  selector:
    app: microservice-a
  ports:
  - port: 80
    targetPort: 8080