# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: microservice-a
spec:
  type: LoadBalancer # Exposes the service externally
  selector:
    app: microservice-a
  ports:
  - port: 80
    targetPort: 8080